// <auto-generated />
using System;
using CalculatorSalarii.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CalculatorSalarii.Migrations
{
    [DbContext(typeof(CalculatorSalariiContext))]
    [Migration("20200903085729_ModifyAngjatTable")]
    partial class ModifyAngjatTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CalculatorSalarii.Models.Angajat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsServiciuDeBaza")
                        .HasColumnType("bit");

                    b.Property<int>("NrPersoaneInIntretinere")
                        .HasColumnType("int");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("VenitBrut")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Angajat");
                });

            modelBuilder.Entity("CalculatorSalarii.Models.ParametriLunari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("ProcentCAM")
                        .HasColumnType("float");

                    b.Property<double>("ProcentCAS")
                        .HasColumnType("float");

                    b.Property<double>("ProcentCASS")
                        .HasColumnType("float");

                    b.Property<double>("ProcentImpozit")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("ParametriLunari");
                });

            modelBuilder.Entity("CalculatorSalarii.Models.StatPlata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AngajatId")
                        .HasColumnType("int");

                    b.Property<int>("ContributieCAS")
                        .HasColumnType("int");

                    b.Property<int>("ContributieCASS")
                        .HasColumnType("int");

                    b.Property<int>("DeducerePersonala")
                        .HasColumnType("int");

                    b.Property<int>("SumaCAM")
                        .HasColumnType("int");

                    b.Property<int>("SumaImpozit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AngajatId");

                    b.ToTable("StatPlata");
                });

            modelBuilder.Entity("CalculatorSalarii.Models.StatPlata", b =>
                {
                    b.HasOne("CalculatorSalarii.Models.Angajat", "Angajat")
                        .WithMany()
                        .HasForeignKey("AngajatId");
                });
#pragma warning restore 612, 618
        }
    }
}
